implemented explicit fileformat option
biowdl/biowdl-input-converter pull request #12
Opened 2021-04-14 13:17 UTC by leipzig

This implements the explicit file format option for this tool (as opposed to autodetect based on suffixes) to deal with Cromwell's unfortunate behavior of renaming files identified by URLs

### Checklist
- [X] Pull request details were added to CHANGELOG.rst

2021-04-16 13:36 UTC, rhpvorderman requested changes
Looks good, thanks!

I just found a few formatting issues. Also, I updated the main branch just now to move the testing to github actions. Can you merge the dev branch back in?

2021-04-16 13:36 UTC, rhpvorderman commented on src/biowdl_input_converter/__init__.py
> +    output_json = samplesheet_to_json(samplesheet=Path(args.samplesheet), fileformat=args.format, old_style_json=args.old_style_json, file_presence_check=not args.skip_file_check, file_md5_check=args
can you put the newlines back in? It is more readable that way.

2021-04-20 19:26 UTC, leipzig commented on src/biowdl_input_converter/__init__.py
> +    output_json = samplesheet_to_json(samplesheet=Path(args.samplesheet), fileformat=args.format, old_style_json=args.old_style_json, file_presence_check=not args.skip_file_check, file_md5_check=args
ok done

2021-04-20 19:28 UTC, leipzig commented
ok I've merged dev in and made the formatting changes

2021-04-21 13:34 UTC, rhpvorderman approved these changes

2021-04-21 13:35 UTC, rhpvorderman commented
Looks good! thanks for adding a test as well.

2021-04-21 13:35 UTC, merged

2021-04-21 13:36 UTC, leipzig commented
Thanks for the merge. I'm determined to get all of BioWDL loaded onto Truwl.com so I'll probably be in touch!

2021-04-23 10:16 UTC, rhpvorderman commented
@leipzig Thanks for the update. I  created a new version which was uploaded into bioconda just now. A new image on quay.io should be available shortly.